### ISSUE TITLE
Need to track core-api changes

### ISSUE THREAD

**Issue by Alexerson** [carltongibson/django-filter#621]
When upgrading coreapi to 2.2.x, I got the following error:
`Exception Value: __new__() got an unexpected keyword argument 'description'`
in
`File "lib/python3.5/site-packages/django_filters/rest_framework/backends.py:104" in get_schema_fields`

https://github.com/core-api/python-client/issues/117

**Comment by carltongibson** [comment]
@Alexerson Thanks for the report. Does the new version solve this (for now)? Do we need to do anything?

**Comment by rpkilby** [comment]
@carltongibson The new version fixes this for the short term. However, they're deprecated and we'll eventually need to create a `coreschema.Schema` instead.

**Comment by carltongibson** [comment]
OK. I'll leave this open. Ta!

**Comment by tbeadle** [comment]
This appears to also be the reason that filter help_text is not displayed in django-rest-framework's autogenerated docs for query string parameters.  In the drf template, it uses `field.schema.description` but `field.schema` is None since it's not getting set in `get_schema_fields`.  If I change it to use `field.description`, the value of the filter's help_text is displayed.

**Comment by jter** [comment]
> This appears to also be the reason that filter help_text is not displayed in django-rest-framework's autogenerated docs for query string parameters. In the drf template, it uses field.schema.description but field.schema is None since it's not getting set in get_schema_fields. If I change it to use field.description, the value of the filter's help_text is displayed.

encountered the same issue.

**Comment by tbeadle** [comment]
FYI, I submitted #667 to fix this issue.

**Comment by carltongibson** [comment]
I just pushed 1.0.3 which addresses a number of small issues with schema generation. This is on-going: we're all still exploring here. But this issue is _under control_ to the extent that it's now actionable. So I'm going to close it. 

I'll take concrete issues in separate tickets.
