### ISSUE TITLE
 i am getting ImportError: cannot import name 'QUERY_TERMS'

### ISSUE THREAD

**Issue by rahul6612** [carltongibson/django-filter#980]
currently i am using **django version 1.8.4** and **django-filter version 0.11.0** while running 
**python manage.py collectstatic** i am getting this error 
```
from django.db.models.sql.constants import QUERY_TERMS
ImportError: cannot import name 'QUERY_TERMS'

```

**Comment by rpkilby** [comment]
Hi @rahul6612. I would recommend checking the versions of your installed packages. My guess is that Django was inadvertently upgrade to 2.1 or later.

**Comment by rahul6612** [comment]
ya django 2x version was installed now its working on django 1.8
