### ISSUE TITLE
DateTimeFromToRangeFilter does not work in v1.1

### ISSUE THREAD

**Issue by zhangqunshi** [carltongibson/django-filter#817]
I have a filter with the following field:
```
    create_time = django_filters.DateTimeFromToRangeFilter(field_name='create_time')
    update_time = django_filters.DateTimeFromToRangeFilter(field_name='update_time')
```
And url is `/api/xxx?create_time_after=2017-11-08+06:30`

Above code is working on v2.0.0dev1, but not working on v1.1, why?

BTW My server is python2.7, and cannot install v2.0.0dev1。

Thanks,
Kris

**Comment by carltongibson** [comment]
> ...why?

Because you're using the v2.0+ naming provided by `SuffixedMultiWidget`. (See [migration guide](https://django-filter.readthedocs.io/en/master/guide/migration.html#multiwidget-replaced-by-suffixedmultiwidget))

1. You'll want to stick to the v1.1. docs. http://django-filter.readthedocs.io/en/1.1.0/index.html
2. "BTW..." — You should upgrade Python. It's a whole new world. 😃

**Comment by zhangqunshi** [comment]
Thanks carltongibson.

Just now i lookup the document, i have to change the search name from "create_time_after" to "create_time_0", right?

[](http://django-filter.readthedocs.io/en/1.1.0/ref/filters.html)

**Comment by carltongibson** [comment]
That's right. 

(In 1.1. you can also manually set `SuffixedMultiWidget` as your widget. It just becomes the default in 2.0)

**Comment by zhangqunshi** [comment]
How to use this SuffixedMultiWidget ?
```
class RangeWidget(SuffixedMultiWidget):
    suffixes = ['after', 'before']


create_time = django_filters.DateTimeFromToRangeFilter(field_name='create_time'， widget=RangeWidget())
```
but i got an error:
`TypeError: __init__() missing 1 required positional argument: 'widgets'`

Can you give me a help?
Thanks

**Comment by rpkilby** [comment]
I believe you can just mix the `SuffixedMultiWidget` with the appropriate range widget. eg, `DateTimeFromToRangeFilter` uses `DateRangeWidget`, so...

```python
class SuffixedDateRangeWidget(SuffixedMultiWidget, DateRangeWidget):
    pass
    
create_time = django_filters.DateTimeFromToRangeFilter(field_name='create_time'， widget=SuffixedDateRangeWidget)
```

**Comment by carltongibson** [comment]
But also, you want to pass the widget class, not an instance.

**Comment by zhangqunshi** [comment]
Thanks a lot, guys.

**Comment by zhangqunshi** [comment]
BTW, i think above code can append to the doc: http://django-filter.readthedocs.io/en/1.1.0/ref/widgets.html?highlight=suffixedmultiwidget

**Comment by carltongibson** [comment]
A PR there would be great.
