### ISSUE TITLE
Unable to loop over filter form fields in template of LinkWidget since Django>=1.11

### ISSUE THREAD

**Issue by tombreit** [carltongibson/django-filter#880]
I'm unable to loop over my ``LinkWidget`` in the template since updating Django from 1.10.x to 1.11. My code crashes with 

```
# django debug error
AttributeError at /articles/
'LinkWidget' object has no attribute 'template_name'
```

Full traceback: http://dpaste.com/0H4XWK0

I've read the Django 1.11 Release Notes and found some references regarding the new template based widget rendering, but can not see how this is related to my django-filter implementation or how I do get rid of this error. I do not even know if this is an error in django-filter or my template code.

Finally, I would just like to render some custom html for my ``LinkWidget``. 

That's the code involved: 

---
```
# filters.py
class ArticleFilter(django_filters.FilterSet):
    language = django_filters.ChoiceFilter(
        label='Language',
        choices=ArticlePage.LANGUAGE_CHOICES,
        widget=LinkWidget(),
    )
```
---
```
# template.html
{% for choice in filter.form.language %}
    {{ choice }}
{% endfor %}
```

Setup: 
* Django (1.11.10)
* django-filter (1.1.0)
* Python 3.5.3

**Comment by rpkilby** [comment]
It would be helpful to see the stack trace.

**Comment by tombreit** [comment]
Dear @rpkilby , sorry, issue updated with traceback.

**Comment by rpkilby** [comment]
Hi @tombreit - thanks for providing the traceback. I'm not completely sure, but it looks to me that this is a small bug in Django. It assumes that subwidgets are compatible with template-based rendering, which may not be the case. 

That said, `LinkWidget` does not have subwidgets, so iterating of the `language` field shouldn't do anything meaningful. You should be able to change your template to just:

```
# template.html
{{ filter.form.language }}
```

**Comment by tombreit** [comment]
Sorry for this late response - just omitting the loop as you suggested did the trick.

**Comment by webconexus** [comment]
I am also running into this issue. How to add styling to the links then when you can't loop over it in your template?

**Comment by mwasn** [comment]
Coming late to the party as I´m running into the same issue. Can someone please explain the trick again?

**Comment by tombreit** [comment]
Dear @webconexus , @mwasn , 
you can loop over the form fields, but not over the subwidgets - something like the following should work: 

```python
{% for filter in filter.form %}
    <div class="class-foo  {% if field.name == 'bar' %} class-bar {% endif %}">
       <strong>{{ filter.label }}</strong>
       {{ filter }}
    </div>
{% endfor %}
```
