### ISSUE TITLE
Latest version TypeError: __init__() got an unexpected keyword argument 'name' but django-filter-1.1.0 works

### ISSUE THREAD

**Issue by elsagong** [carltongibson/django-filter#950]
I am learning a Django project with django rest framework, the server works in version of django-filter 1.1.0, but if I update django-filter to 2.0.0, no matter how I changed the code, I always got the error of `TypeError: __init__() got an unexpected keyword argument 'name'` ,  only this way to use 1.1.0?  Could you please help me with this issue? 

Thank you so much for any advice!
Best regards.

**Comment by carltongibson** [comment]
Please read the migration guide re Upgrading to 2.0. https://django-filter.readthedocs.io/en/master/guide/migration.html#filter-name-renamed-to-filter-field-name-792
